'use strict';

/**
 * Payment Service — orchestrates donation initiation with real gateway calls.
 *
 * This file extends the existing donationService.initiate() to use the
 * PaymentGateway adapters. Drop this in as a replacement for the MVP stub.
 *
 * Flow:
 * 1. Validate request + parish
 * 2. Create donation record (INITIATED)
 * 3. Call gateway adapter → get checkout payload + URL
 * 4. Transition donation to PENDING
 * 5. Return checkout data to client
 * 6. Client redirects user to provider payment page
 * 7. Provider calls /webhook/:provider on completion
 * 8. Webhook handler verifies signature, transitions SUCCESS/FAILED
 */

const { PaymentGateway } = require('../payment/gateway');
const { Donation, Parish, AuditLog } = require('../../models');
const { audit } = require('../utils/auditLogger');
const { NotFoundError, PaymentError } = require('../errors');

/**
 * Enhanced initiate — returns real checkout URL for client redirect.
 * Replaces the MVP stub in donations/index.js donationService.initiate().
 */
async function initiateWithGateway({ userId, parishId, amount, currency, provider, message, isAnonymous }, req) {
  // 1. Validate parish
  const parish = await Parish.findById(parishId).lean();
  if (!parish || !parish.isActive || !parish.isVerified) {
    throw new NotFoundError('Parish');
  }

  // 2. Create donation record (idempotencyKey generated by pre-validate hook)
  const donation = await Donation.create({
    userId, parishId, amount, currency, provider, message, isAnonymous,
  });

  await audit.donation(
    AuditLog.ACTIONS.DONATION_INITIATED, userId, donation._id,
    { amount, currency, provider, parishId }, req
  );

  try {
    // 3. Build checkout with provider adapter
    const checkout = await PaymentGateway.buildCheckout(provider, {
      ...donation.toObject(),
      // Pass parish name for provider description
      parishName: parish.name,
    });

    // 4. Transition to PENDING — payment is now in provider's hands
    await donation.transitionStatus('PENDING', 'system', `Checkout created with ${provider}`);

    await audit.donation(
      AuditLog.ACTIONS.DONATION_PENDING, userId, donation._id,
      { provider, checkoutUrl: checkout.checkoutUrl }, req
    );

    return {
      donationId:     donation._id,
      idempotencyKey: donation.idempotencyKey,
      status:         donation.status,
      checkout,       // { provider, checkoutUrl, payload } — client uses this
    };

  } catch (err) {
    // Gateway call failed — cancel the donation so user can retry
    try {
      await donation.transitionStatus('CANCELLED', 'system', `Gateway error: ${err.message}`);
    } catch { /* transition failure is non-fatal */ }

    throw new PaymentError(
      `Payment gateway error for ${provider}: ${err.message}`,
      provider
    );
  }
}

/**
 * Webhook processor — enhanced version using PaymentGateway adapter.
 * Replaces the inline helpers in donations/index.js handleWebhook.
 */
async function processWebhook(provider, rawBody, headers, payload) {
  // 1. Verify signature via adapter (throws WebhookSignatureError on failure)
  PaymentGateway.verifyWebhookSignature(provider, rawBody, headers);

  // 2. Extract provider transaction ID
  const providerTxId = PaymentGateway.extractTxId(provider, payload);
  if (!providerTxId) {
    await audit.webhook(AuditLog.ACTIONS.WEBHOOK_REJECTED,
      { provider, reason: 'missing_tx_id' }, 'failure');
    return { acknowledged: true, reason: 'missing_tx_id' };
  }

  // 3. Find donation — must use primary read for consistency
  const donation = await Donation.findOne({ provider, providerTransactionId: providerTxId })
    .select('+webhookPayloadHash +providerMetadata')
    .read('primary');

  // 3a. Also try by idempotency key (some providers return our reference)
  let resolvedDonation = donation;
  if (!resolvedDonation) {
    const ourRef = payload?.client_reference || payload?.externalId || payload?.order_id;
    if (ourRef) {
      resolvedDonation = await Donation.findOne({ idempotencyKey: ourRef })
        .select('+webhookPayloadHash +providerMetadata')
        .read('primary');
    }
  }

  if (!resolvedDonation) {
    await audit.webhook(AuditLog.ACTIONS.WEBHOOK_RECEIVED,
      { provider, providerTxId, reason: 'unknown_tx' }, 'warning');
    // Acknowledge unknown transactions — provider will NOT retry on 200
    return { acknowledged: true, reason: 'unknown_transaction' };
  }

  // 4. Idempotency — already in terminal state
  const TERMINAL = ['SUCCESS', 'FAILED', 'REFUNDED', 'CANCELLED'];
  if (TERMINAL.includes(resolvedDonation.status)) {
    return { acknowledged: true, idempotent: true, status: resolvedDonation.status };
  }

  await audit.webhook(AuditLog.ACTIONS.WEBHOOK_RECEIVED,
    { provider, providerTxId, donationId: resolvedDonation._id });

  // 5. Duplicate payload detection (same payload hash = retry, not new event)
  const { createHash } = require('crypto');
  const payloadHash = createHash('sha256').update(JSON.stringify(payload)).digest('hex');

  if (resolvedDonation.webhookPayloadHash === payloadHash) {
    return { acknowledged: true, duplicate: true };
  }

  // 6. Store provider transaction reference + payload hash
  resolvedDonation.providerTransactionId = providerTxId;
  resolvedDonation.webhookPayloadHash    = payloadHash;
  resolvedDonation.webhookReceivedAt     = new Date();

  // Store limited provider metadata (size-capped by model validator)
  resolvedDonation.providerMetadata = {
    provider,
    txId:       providerTxId,
    receivedAt: new Date().toISOString(),
    // Do NOT store full payload — may contain PII or large fields
  };

  // 7. Extract outcome and fees from adapter
  const isSuccess = PaymentGateway.extractSuccess(provider, payload);
  const fees      = PaymentGateway.extractFees(provider, payload);

  if (fees !== null && typeof fees === 'number') {
    resolvedDonation.fees = fees;
  }

  const newStatus = isSuccess ? 'SUCCESS' : 'FAILED';

  // 8. Transition status — auto-saves and computes netAmount
  await resolvedDonation.transitionStatus(newStatus, 'webhook', `${provider}: ${newStatus}`);

  // 9. Post-success actions
  if (newStatus === 'SUCCESS') {
    await Parish.incrementDonationStats(resolvedDonation.parishId, resolvedDonation.netAmount);

    await audit.webhook(
      AuditLog.ACTIONS.DONATION_SUCCESS,
      {
        provider,
        providerTxId,
        donationId: resolvedDonation._id,
        amount:     resolvedDonation.amount,
        netAmount:  resolvedDonation.netAmount,
      }
    );
  } else {
    await audit.webhook(
      AuditLog.ACTIONS.DONATION_FAILED,
      { provider, providerTxId, donationId: resolvedDonation._id }
    );
  }

  await audit.webhook(AuditLog.ACTIONS.WEBHOOK_VERIFIED, { provider, status: newStatus });

  return { acknowledged: true, status: newStatus, donationId: resolvedDonation._id };
}

module.exports = { initiateWithGateway, processWebhook };
